name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 1000
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          # git add -A .
          git add profile-3d-contrib/profile-night-rainbow.svg
          git commit -m "generated"
          git push
